[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "sms-irc"
version = "0.1.0"

[dependencies]
derive_builder = "0.5"
failure = "0.1"
futures = "0.1"
chrono = "0.4"
image = "0.19"
irc = "0.13"
log = "0.4"
log4rs = "0.8"
qrcode = "0.7"
r2d2 = "0.8"
r2d2-diesel = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"
toml = "0.4"

[dependencies.diesel]
features = ["postgres", "serde_json"]
version = "1.0"

[dependencies.huawei-modem]
git = "https://github.com/eeeeeta/huawei-modem"

[dependencies.whatsappweb]
git = "https://github.com/eeeeeta/whatsappweb-rs"
