[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "sms-irc"
version = "0.1.0"

[dependencies]
failure = "0.1"
log4rs = "0.8"
futures = "0.1"
irc = "0.13"
log = "0.4"
r2d2 = "0.8"
r2d2-diesel = "1.0"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
tokio-timer = "0.2"
toml = "0.4"

[dependencies.diesel]
features = ["postgres"]
version = "1.0"

[dependencies.huawei-modem]
git = "git://github.com/eeeeeta/huawei-modem"
